// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokedex.api.Data;

#nullable disable

namespace Pokedex.api.DataMigrations
{
    [DbContext(typeof(PokedexContext))]
    [Migration("20240316000710_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Pokedex.api.Entities.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("Pokedex.api.Entities.Pokemon", b =>
                {
                    b.Property<int?>("Pn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ElementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Pn");

                    b.HasIndex("ElementId");

                    b.ToTable("Pokedex");
                });

            modelBuilder.Entity("Pokedex.api.Entities.Pokemon", b =>
                {
                    b.HasOne("Pokedex.api.Entities.Element", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId");

                    b.Navigation("Element");
                });
#pragma warning restore 612, 618
        }
    }
}
