// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokedex.api.Data;

#nullable disable

namespace Pokedex.api.DataMigrations
{
    [DbContext(typeof(PokedexContext))]
    [Migration("20240315223552_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Pokedex.api.Entities.Pokemon", b =>
                {
                    b.Property<int>("Pn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipoa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipob")
                        .HasColumnType("TEXT");

                    b.HasKey("Pn");

                    b.ToTable("Pokedex");
                });
#pragma warning restore 612, 618
        }
    }
}
