GET http://localhost:5007/pokemons

###
GET http://localhost:5007/pokemons/150

###
POST http://localhost:5007/pokemons
Content-Type: application/json

{
    "pn": 151,
    "name": "Mew",
    "elementId": 11,
    "description": "A mythical Pokémon of South America which had been thought extinct. A growing number of people have seen it recently."
}

###
PUT http://localhost:5007/pokemons/151
Content-Type: application/json

{
    "pn": 151,
    "name": "Mew",
    "elementId": 11,
    "description": "A mythical Pokémon of South America which had been thought extinct. A growing number of people have seen it recently."
}

###
DELETE http://localhost:5007/pokemons/151